name: Scrape unprocessed ballots status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Scrape 2023
        run: deno run --allow-write=unprocessed-ballots-status.csv --allow-net ./scrape.ts
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git pull
          git add unprocessed-ballots-status.csv
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push